defaultIcon: "qiita"
items:
  - title: "Datadog Japan 有志ブログのご紹介"
    url: "https://qiita.com/AoTo0330/items/0ce1505b5a1b2d080ad8"
    date: "2025-12-01T00:28:38+09:00"
  - title: " Google Cloud おすすめ学習方法5選【初学者~中級者向け】"
    url: "https://qiita.com/AoTo0330/items/8eb5beef716a3b1eca49"
    date: "2024-12-30T02:28:20+09:00"
  - title: "Cloud Run を GKE の代替として利用する"
    url: "https://qiita.com/AoTo0330/items/36727475de42eab1fa7e"
    date: "2024-12-25T23:46:54+09:00"
  - title: "マルチステージビルドを完全に理解して Cloud Run のセキュリティを向上する"
    url: "https://qiita.com/AoTo0330/items/4d2c0fa6a127ef5b4b1d"
    date: "2024-12-25T21:05:37+09:00"
  - title: "Cloud Run services トレース監視「だいたいぜんぶ」"
    url: "https://qiita.com/AoTo0330/items/d542b24a065d871571e7"
    date: "2024-12-25T21:04:21+09:00"
  - title: "Cloud Run services ログ監視「だいたいぜんぶ」"
    url: "https://qiita.com/AoTo0330/items/f6e1ca508384a3b8fc7a"
    date: "2024-12-25T20:25:10+09:00"
  - title: "クラウド認定資格を更新し続ける理由"
    url: "https://qiita.com/AoTo0330/items/762b7e7c0aa9b7a3f877"
    date: "2024-12-24T00:55:35+09:00"
  - title: "Cloud Run services メトリクス監視「だいたいぜんぶ」"
    url: "https://qiita.com/AoTo0330/items/d02f7daab46ed54b4339"
    date: "2024-12-24T00:20:26+09:00"
  - title: "え、APM と分散トレースは同じじゃないですよ？"
    url: "https://qiita.com/AoTo0330/items/6441201e3daddfac9029"
    date: "2024-12-23T14:47:42+09:00"
  - title: "OpenTelemetry Certified Associate(OTCA) 最速受験記"
    url: "https://qiita.com/AoTo0330/items/2c0ff35acfb5fdf6fd11"
    date: "2024-12-21T02:23:10+09:00"
  - title: "で、Cloud Run と App Engine って何が違うの？"
    url: "https://qiita.com/AoTo0330/items/6b31bb6c042e2f285168"
    date: "2024-12-20T21:32:36+09:00"
  - title: "【Oura × Datadog】API の特性を活かした効率的な連携アプローチ"
    url: "https://qiita.com/AoTo0330/items/c518033a5b8c217672c0"
    date: "2024-12-20T05:20:39+09:00"
  - title: "2024年の技術コミュニティ活動を振り返る"
    url: "https://qiita.com/AoTo0330/items/87a4833e4eabaf9a7b85"
    date: "2024-12-20T02:30:06+09:00"
  - title: "監視データの特性 - 分散トレースのサンプリング"
    url: "https://qiita.com/AoTo0330/items/f87bd984bebe4f5e1b52"
    date: "2024-12-19T09:40:18+09:00"
  - title: "Datadog を使いこなす 7 Tips "
    url: "https://qiita.com/AoTo0330/items/9aa324f3f8f949e8094d"
    date: "2024-12-18T17:01:13+09:00"
  - title: "監視データの特性 - ログの保管と転送"
    url: "https://qiita.com/AoTo0330/items/51327a7201527ef9d0bf"
    date: "2024-12-17T22:43:07+09:00"
  - title: "AWS re:Invent 2024 で AWS Observability はどう変わったか"
    url: "https://qiita.com/AoTo0330/items/2911c64e89d878d7c555"
    date: "2024-12-17T02:16:58+09:00"
  - title: "監視データの特性 - メトリクスの次元とカーディナリティ"
    url: "https://qiita.com/AoTo0330/items/95573254c1c2e3747fda"
    date: "2024-12-16T15:05:21+09:00"
  - title: "AWS re:Invent 2024 で発表された Datadog の新機能: AWS integration & support 編"
    url: "https://qiita.com/AoTo0330/items/6b2686ce2ad01ffa54cf"
    date: "2024-12-15T02:24:19+09:00"
  - title: "AWS re:Invent 2024 で発表された Datadog の新機能: Datadog Product 編"
    url: "https://qiita.com/AoTo0330/items/a5c74a9c4a30257a783d"
    date: "2024-12-11T07:31:44+09:00"
  - title: "【図解】OpenTelemetry × Datadog "
    url: "https://qiita.com/AoTo0330/items/188109aaf3500941fc6d"
    date: "2024-12-10T01:12:06+09:00"
  - title: "DASH 2024 で発表された Datadog の最新機能: Act 編"
    url: "https://qiita.com/AoTo0330/items/e0ae92644497561ee357"
    date: "2024-12-09T09:25:17+09:00"
  - title: "DASH 2024 で発表された Datadog の最新機能: Secure 編"
    url: "https://qiita.com/AoTo0330/items/bafb7a2c36bc530df9b6"
    date: "2024-12-07T21:45:38+09:00"
  - title: "DASH 2024 で発表された Datadog の最新機能: Observe 編"
    url: "https://qiita.com/AoTo0330/items/35551400a9fc3fa5a67a"
    date: "2024-12-06T05:32:09+09:00"
  - title: "Datadog integrations Deep Dive - Google Cloud 編"
    url: "https://qiita.com/AoTo0330/items/bfa3f204b491f83bcab1"
    date: "2024-12-05T10:33:30+09:00"
  - title: "Datadog integrations Deep Dive - Azure 編"
    url: "https://qiita.com/AoTo0330/items/82aa9d5bb9473f24d1f8"
    date: "2024-12-04T20:39:47+09:00"
  - title: "Datadog integrations Deep Dive - AWS 編"
    url: "https://qiita.com/AoTo0330/items/ae8d5989f41171b1647b"
    date: "2024-12-03T11:53:56+09:00"
  - title: "【完全解説】4大クラウドの Datadog integrations アーキテクチャ【2024年版】"
    url: "https://qiita.com/AoTo0330/items/33d7b58a3cfddcbd3fe2"
    date: "2024-11-01T22:53:23+09:00"
  - title: "詳細解説 Cloud Run 最新アップデート"
    url: "https://qiita.com/AoTo0330/items/3e47dfbbcfe8b38591e1"
    date: "2024-04-30T19:29:55+09:00"
  - title: "で、Cloud Functions と Cloud Run って何が違うの？"
    url: "https://qiita.com/AoTo0330/items/1977c1ae14381d274c0b"
    date: "2024-01-31T07:59:13+09:00"
  - title: "Buildpacks が Google Cloud で使える件"
    url: "https://qiita.com/AoTo0330/items/be487ae1c497651e2f8e"
    date: "2023-12-26T23:10:03+09:00"
  - title: "Azure Metrics Data plane API で何が変わったのか？"
    url: "https://qiita.com/AoTo0330/items/10c18f9de0dbe4fce61a"
    date: "2023-12-25T17:44:36+09:00"
  - title: "Qiita Advent Calendar を個人で完走した"
    url: "https://qiita.com/AoTo0330/items/9617af316ac84f086483"
    date: "2023-12-25T04:15:27+09:00"
  - title: "【Google Cloud Next Tokyo ’23】Datadog で GKE とマネージドサービスを効率的に運用する方法【Datadog】"
    url: "https://qiita.com/AoTo0330/items/17dba76a7282c4b93fe7"
    date: "2023-12-25T03:34:38+09:00"
  - title: "Datadog Agent の豆知識"
    url: "https://qiita.com/AoTo0330/items/5125e468232c0196d916"
    date: "2023-12-24T21:57:42+09:00"
  - title: "OpenTelemetry と Prometheus"
    url: "https://qiita.com/AoTo0330/items/ae23848595c137896994"
    date: "2023-12-22T22:52:52+09:00"
  - title: "eBPF で SRE を始めよう！"
    url: "https://qiita.com/AoTo0330/items/433e46ad6d78a86e07b8"
    date: "2023-12-21T23:50:41+09:00"
  - title: "Four Keys って何？ | Datadog DORA Metrics の可視化"
    url: "https://qiita.com/AoTo0330/items/3d3eda7ef651312f22a6"
    date: "2023-12-21T10:17:03+09:00"
  - title: "AWS と考える Observability のベストプラクティス"
    url: "https://qiita.com/AoTo0330/items/3731f2ff7fbbe1299ca9"
    date: "2023-12-21T08:54:09+09:00"
  - title: "Prometheus メトリクス入門"
    url: "https://qiita.com/AoTo0330/items/a1340d1b906bc39411bc"
    date: "2023-12-18T23:43:10+09:00"
  - title: "Observability のベストプラクティスを実現：Datadog Service Scorecards によるサービスレベルの自動評価と可視化"
    url: "https://qiita.com/AoTo0330/items/7f44f87644cd853ba6a4"
    date: "2023-12-17T23:50:46+09:00"
  - title: "RUM サンプリングのすゝめ"
    url: "https://qiita.com/AoTo0330/items/6018b78b04e3fad0e177"
    date: "2023-12-16T09:14:31+09:00"
  - title: "Datadog DBM で AlloyDB を監視する"
    url: "https://qiita.com/AoTo0330/items/298fe7dadea7a0be4c5d"
    date: "2023-12-15T23:16:55+09:00"
  - title: "Oracle Cloud Infrastructure 入門のすゝめ"
    url: "https://qiita.com/AoTo0330/items/09425e64523ef9ea0fb3"
    date: "2023-12-14T02:54:38+09:00"
  - title: "Cloud Run で Datadog Agent をサイドカーで動かして、どうなったか【裏側】"
    url: "https://qiita.com/AoTo0330/items/17ff9951b59609c21718"
    date: "2023-12-13T04:24:41+09:00"
  - title: "Datadog Go APM の Compile-time instrumentation"
    url: "https://qiita.com/AoTo0330/items/f36eae6fb00061b6a0f7"
    date: "2023-12-12T05:15:22+09:00"
  - title: "Amazon Q vs Duet AI【個人的まとめ】"
    url: "https://qiita.com/AoTo0330/items/63e93838b04848010bc1"
    date: "2023-12-11T23:54:05+09:00"
  - title: "Oura API V2 を読み解いて、Datadog にヘルスケアデータを連携する"
    url: "https://qiita.com/AoTo0330/items/24277b04be2345b658a1"
    date: "2023-12-10T23:14:17+09:00"
  - title: "Kubernetes のコスト最適化ゴールデンシグナル"
    url: "https://qiita.com/AoTo0330/items/144b305a560ad60bb0cb"
    date: "2023-12-09T12:40:58+09:00"
  - title: "技術コミュニティが人生を変えた話"
    url: "https://qiita.com/AoTo0330/items/7d320adc43d356885d67"
    date: "2023-12-08T20:45:24+09:00"
  - title: "Datadog って OpenTelemetry に対応しているの？"
    url: "https://qiita.com/AoTo0330/items/b9a758555b7e049eca9f"
    date: "2023-12-07T18:07:44+09:00"
  - title: "Azure App Spaces と Observability"
    url: "https://qiita.com/AoTo0330/items/3fcfe310c3edb7dcceb3"
    date: "2023-12-05T20:56:44+09:00"
  - title: "AWS re:Invent 2023 で発表された Datadog の新機能: AWS integrations 編"
    url: "https://qiita.com/AoTo0330/items/f0f69bac034001858fa9"
    date: "2023-12-04T21:35:05+09:00"
  - title: "AWS re:Invent 2023 で発表された Datadog の新機能: Datadog Product 編"
    url: "https://qiita.com/AoTo0330/items/8cc0e5ff5ea5ccf4c431"
    date: "2023-12-03T05:45:33+09:00"
  - title: "Amazon CloudWatch Application Signals 徹底解説"
    url: "https://qiita.com/AoTo0330/items/4d3cf0f6126f1a2a76c5"
    date: "2023-12-03T00:55:05+09:00"
  - title: "2023年の技術コミュニティ活動を振り返る"
    url: "https://qiita.com/AoTo0330/items/804bf52b793564ce63f9"
    date: "2023-12-02T20:00:03+09:00"
  - title: "Qiita Advent Calendar を個人で完走する"
    url: "https://qiita.com/AoTo0330/items/df7cb404b88c73156ca8"
    date: "2023-12-01T14:18:10+09:00"
  - title: "Azure App Spaces と Azure Developer CLI"
    url: "https://qiita.com/AoTo0330/items/0075c55d2c4bcf4acbe2"
    date: "2023-08-16T11:19:44+09:00"
  - title: "Cloud Run で Datadog Agent をサイドカーとして動かす"
    url: "https://qiita.com/AoTo0330/items/35a840462f219596e39d"
    date: "2023-05-21T16:22:23+09:00"
  - title: "Datadog の AWS Integration for Multi-Accounts (AWS CloudFormation StackSets) 徹底解説"
    url: "https://qiita.com/AoTo0330/items/9ee7077af1a3c660af4e"
    date: "2023-04-26T16:25:35+09:00"
  - title: "3大クラウドのDatadog Integrations アーキテクチャ"
    url: "https://qiita.com/AoTo0330/items/545a229fd33d92c01562"
    date: "2022-12-08T03:43:28+09:00"
  - title: "Qiitaを始めるにあたって"
    url: "https://qiita.com/AoTo0330/items/6ee42ad975397f10c13c"
    date: "2022-01-10T22:01:27+09:00"
