defaultIcon: "zenn"
items:
  - title: "大規模 Cloud Run 環境を支える Datadog の Terraform 実装"
    url: "https://zenn.dev/datadog/articles/datadog-cr-tf"
    date: "2025-12-03T07:00:00+09:00"
  - title: "あなたの SRE チームを促進させる、Bits AI SRE 偉いところ"
    url: "https://zenn.dev/datadog/articles/bits-ai-sre-intro"
    date: "2025-12-02T09:15:00+09:00"
  - title: "Datadog に Google Cloud のログをセキュアに送信する"
    url: "https://zenn.dev/datadog/articles/datadog-gc-logs-dataflow"
    date: "2024-01-18T09:41:00+09:00"
  - title: "Cloud Run で GMP を利用する際の注意点"
    url: "https://zenn.dev/aotolog/articles/cr-gmp-notes"
    date: "2023-12-18T21:44:00+09:00"
  - title: "Next.js に Datadog APM を導入する際の注意点"
    url: "https://zenn.dev/datadog/articles/nextjs-datadog-apm"
    date: "2023-12-06T22:39:00+09:00"
